# A single radar detection

Measurement range                   # range measurement [m]
Measurement radial_speed            # radial speed measurement [m/s]

Measurement azimuth                 # azimuth angle measurement [rad]
Measurement elevation               # elevation angle measurement [rad]

Measurement rcs                     # cross-section measurement [m^2]
Measurement power                   # power measurement [dB]
Measurement noise                   # noise measurement [dB]

Coverage    coverage                # coverage (depends on radar operating mode)
Measurement existance_probability   # existance probability [0..1] (false-alarm indicator)
